apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: color-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
        - name: color-app
          image: edsonbsaantos/color-app:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: Estudos
            - name: FLASK_ENV
              value: development
            - name: APP_NAME
              value: Color App
            - name: APP_COLOR
              value: red
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          imagePullPolicy: Always