apiVersion: v1
kind: Service
metadata:
  name: color-app
  namespace: color-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: color-app
  type: LoadBalancer
