apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rollout-color-app
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: color-app
  targetCPUUtilizationPercentage: 50
